### ISSUE TITLE
withDS doesn't use the DrawState's Color

### ISSUE THREAD

**Issue by sjakobi** [google/codeworld#1000]
https://github.com/google/codeworld/blob/24778237c19a39e77b415d43dc8e681493a0e539/codeworld-api/src/CodeWorld/Driver.hs#L405-L409

Note that `col` is unused. I'm not sure whether this is how things should be.

This would be easier to catch with `-Wall` and `-Werror` enabled.

**Comment by cdsmith** [comment]
The color is applied separately using `applyColor`.

The reason is a little subtle.  Imagine an expression like `scaled 1 5 (circle 1)`.  This should draw an ellipse that's 1 unit wide and 5 units tall, but with a **line** that's uniformly one pixel in thickness.  If the code did the JavaScript `stroke()` call with the scaling in effect, then that line thickness would also be scaled in the y dimension.  So we end up wanting do something like this:

    withDS ds $ followPath ...
    applyColor ds
    stroke

It wouldn't be a problem to also set the color in withDS, if you prefer it that way.  But that color would be lost after drawing because withDS wraps a `saveRestore` around the transformation.

**Comment by cdsmith** [comment]
I don't see any reason to add an unnecessary call to `setColor` on the JavaScript side, so I'll assume this is resolved by the explanation above.
