### ISSUE TITLE
Guide problem: lettering("Camille") produces distorted text

### ISSUE THREAD

**Issue by bawolk** [google/codeworld#1043]
**Shared Program**: https://code.world/#P6MPHcjojrCc036o2U2ju_g

**Description**
Following the Guide, running
```
program = drawingOf(nametag)
nametag = lettering("Camille")
```
produces distorted text.
![Screenshot_2019-07-04_13-11-09](https://user-images.githubusercontent.com/375816/60686518-21a3ad00-9e5e-11e9-86f9-8f40dc245c17.png)
Using Firefox 67.0.4 under Ubuntu 18.04.

**Comment by cdsmith** [comment]
That's bizarre.  I can only check right now on ChromeOS, but it seems to render fine in Chrome.  And I cannot imagine would cause this.

**Comment by bawolk** [comment]
Runs fine in Chrome on my computer as well, so it must be some issue with Firefox.

**Comment by cdsmith** [comment]
I have a suspicion of what this might be about.  I recently did a cleanup that removed the last vestiges of the old fixed-size 500 x 500 pixel screen.  One consequence of this was that instead of setting the font to 25px, text is drawn at 1px size, with a transform to increase the size.  It might be that FireFox's font layout code tries to round some things to the nearest pixel, and so having the text nominally in 1px size causes poor positioning of characters.  (It looks like the core problem is that thin letters like i and l don't advance the position at all.)

I can try to work around this, by changing the font code to draw at a larger nominal size with a scaling factor to fix it.

**Comment by cdsmith** [comment]
@bawolk If my guess was correct, then this should be fixed.  Can you try again?

Thanks!

**Comment by bawolk** [comment]
Your guess was correct.  Works fine now.

**Comment by cdsmith** [comment]
Thanks so much for the bug report.  I wouldn't have noticed that for a long time.
