### ISSUE TITLE
GHCJS runtime error

### ISSUE THREAD

**Issue by bergey** [google/codeworld#113]
One of my students, @dashhalpern, is encountering a bug where the code below displays the Codeworld logo, superimposed on his intended output, and the error below on the JS console.  The bug only manifests when he is logged in.  The code seems to run fine when I'm logged in, and when not logged in.  

The error looks to me like a bug in GHCJS.  Let me know if I can help reproduce this or narrow down the cause.

```
Javascript Console:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (compile, line 0)
[Error] TypeError: 'undefined' is not an object (evaluating 's.length')
	h$follow (rts.js, line 6377)
	h$markThread (rts.js, line 6315)
	h$gc (rts.js, line 6239)
	h$scheduler (rts.js, line 9612)
	h$mainLoop (rts.js, line 9699)
	(anonymous function) (rts.js, line 10169)
```

``` haskell
import Prelude ()
import HaskellPrelude
import CodeWorld


main = pictureOf move

l :: [Point]
l = [(1,1),(-1,1),(-2,-2),(2,2)]

move :: Picture
move = translate (rectangle (9, 3), (totx l), (toty l))--line (totx l / (len l)) (toty l / len l) t

totx :: [Point] -> Number
totx [] = 0
totx ((x,y):xs) = x + totx xs 

toty :: [Point] -> Number
toty [] = 0
toty ((x,y):xs) = y + totx xs 


len :: [Point] -> Number
len[] = 0
len ((x,y):xs) = 1 + totx xs 
```

**Comment by cdsmith** [comment]
Eep, between being out of town and busy, I somehow missed this report!

I think there are two possibilities:
1. At some point recently, I screwed up and left the server in an inconsistent state after making a change to the standard library.  If this happened during that incident, it should have since fixed itself.
2. Sometimes, these things happen because of browser caching.  If that's it, then this is a dup of #105, but a short-term solution would be to clear browser cache.

Let me know if either of those solves the problem?  If not, I'll dig deeper.

**Comment by bergey** [comment]
The problem hasn't recurred.  I think the two possibilities you mention are likely.  Thanks.
