### ISSUE TITLE
install.sh cabal haddock --html needs an output directory

### ISSUE THREAD

**Issue by blackgnezdo** [google/codeworld#1178]
This also seems to be related to cabal-3.

**Description**
```
===== IN codeworld-base, RUNNING: cabal haddock --html
cabal: option `--html' requires an argument DIR

========== Aborting: Command failed. ==========
DIRECTORY: codeworld-base
COMMAND  : cabal haddock --html
EXIT CODE: 1
===============================================
gnezdo@os-ws:~/codeworld$ echo $?
1
```

**Comment by cdsmith** [comment]
Up until now, `cabal` has put this into `dist/doc/html` in the project directory.  There are symlinks set up that expect this.  I suppose we should continue with that path.

I suppose at the same time that these changes are made, we'd also want to advise people that they need to upgrade to cabal 3.0 if they haven't already, since this does NOT look like a backward-compatible change.

**Comment by cdsmith** [comment]
Subsumed into #1181

**Comment by Carina-Cai** [comment]
I have tried `cabal haddock --html -o dist/doc/html` but it does not work. How exactly do we add the directory?

**Comment by cdsmith** [comment]
@Carina-Cai If you just need to add a directory, then `mkdir -p` would be my assumption.

If there's something else wrong, can you provide more details on what is happening?  I don't have time to try myself at the moment.

**Comment by Carina-Cai** [comment]
Hi Smith, thanks so much for your help! It was solved already.
