### ISSUE TITLE
Always add new line after syntax highlighting on Android

### ISSUE THREAD

**Issue by mchav** [google/codeworld#131]
After typing a word and pressing space on Android, the line I am currently typing is moved to a new line. This happens for every word. Erasing is also a pain.

**Comment by cdsmith** [comment]
Do you have the same problem in the demo window at http://codemirror.net/?

**Comment by cdsmith** [comment]
I tried this in the demo windows at codemirror.net, and I often see the same thing happen there.  I'm afraid the answer to this one is to just escalate upstream.

**Comment by cdsmith** [comment]
One comment at https://github.com/codemirror/CodeMirror/issues/3654 claims that this is caused by the "active-line" addon, which is indeed used here.  I find the addon very useful in practice, though.  (Without it, it's surpisingly hard to actually locate the cursor looking over a student's shoulder.)

I suspect a good start here would be to either look into fixing the active-line addon, or just detect that we're on a mobile browser, and disable it if so.

**Comment by cdsmith** [comment]
I've disabled active-line only on mobile devices.
