### ISSUE TITLE
Data.Map or similar for codeworld-base?

### ISSUE THREAD

**Issue by bbarker** [google/codeworld#1339]
Data.Map could fill several roles - 
 - Provide an indexed data structure
   - Sparse matrices (ok, just kidding, sort of, but want a way to store data associated with the coordinate plane)
 - Introduce the idea that a Map is sot of like a function (well, it is a partial function, so we need default values to make it a function). But Maps have the advantage of being manipulable, unlike functions (there's no `Eq`, `Show`, etc for functions).
 - Maps are easy to use, but not as nice as `data` types for most cases as they aren't well typed, but are more amenable to large, dynamic mappings.

**Comment by cdsmith** [comment]
There's no Ord type class, so an efficient `Map` with polymorphic keys isn't possible.  You could build a newtype wrapper around `[(a, b)]`, I suppose?

> there's no Eq, Show, etc for functions

There are no type classes at all, for any types.  But yeah, in general it's possible to implement operations on finite maps that aren't possible for functions.

Here's a broader point: in order to add something nontrivial to `codeworld-base`, what I'm really looking for is to be convinced that it will be used by enough students to offset the inherent cost of making the API more complex.  The best way to do that is to plan on three stages:

1. Implement the API you want in CodeWorld itself, and use import-by-hash to build compelling examples, and iterate on the design.
2. Send a pull request to add a module to the Extras hierarchy.  These are minimally curated and I'm happy to throw in anything people find useful.
3. Once it's been successfully used in a non-trivial way, start to think about whether to move it out of Extras, either into the Prelude (probably) or into a separate fully-curated module (I've only done that so far with the `Sketches` module, just because the number of exported symbols was so high).

**Comment by cdsmith** [comment]
My tentative conclusion is that this isn't a good direction to go down.  The `Ord` problem makes it essentially impossible to do a good job.  I'll leave this open for a while longer so as not to cut off possible communication, but close it if there's no further argument in favor.

In the end, it's not too hard to do something like:

```
type Dictionary a b = [(a, b)]
emptyDictionary = []
dictionaryWith(dictionary, key, value) =
  [(key, value)] ++ dictionaryWithout(dictionary, k)
dictionaryWithout(dictionary, key) =
  [(k, v) | (k, v) <- dictionary, k /= key ]
hasDefinition(dictionary, key) =
  any([ k == key | (k, v) <- dictionary ])
definitionOf(dictionary, key)
  | hasDefinition(dictionary, key) = defs # 1
  | otherwise = error("Looked up a word that doesn't exist")
  where defs = [ v | (k, v) <- dictionary, k == key ]
```

but I'm not convinced enough students will ever use it to be worth the effort; and I'm not concerned precisely because it is so easy to implement when needed.  In any case, most students won't need all those operations, or won't ever want to update existing keys, etc., and their job will be even easier.
