### ISSUE TITLE
Importing Haskell base from educational dialect is complicated

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1477]
**Program:** https://code.world/#PYDIn5f3T8yBXTEwwjm7KIQ

**Comment:**

I'm sorry but I can't figure out why I can't call foldl or foldl1 or foldl' or foldl1' with (&) as the function, on a list of Pictures.  I also tried importing Data.List but that caused an error.

**Message:**

    program.hs:13:9-15: error: 
        Variable not in scope:
          foldl1' :: (Picture -> Picture -> Picture, [Picture]) -> t

**Comment by cdsmith** [comment]
This looks to be a user who is expecting Haskell, but ended up in the educational dialect instead.  The educational dialect hides base, so modules from base cannot be imported.

https://code.world/#P9l8zeTy2Jl4bdGLVes7kAg gets a little closer to the intended usage, though there are now type errors with the use of `foldl1'` that would need to be fixed.  In any case, this is definitely not the intended use of CodeWorld's educational dialect, and this user would probably be better served by the Haskell dialect at http://code.world/haskell

**Comment by cdsmith** [comment]
If one does want to import Haskell's standard `base` package in the educational dialect, there are several impediments to doing so:

1. `base` is hidden by default.  There is already a custom build step that looks for package imports and exposes those packages during the build if they exist.  So this can be overcome by using a package import, like this:
```
import "base" Data.List (foldl1')
```
2. Once `base` is exposed, the default import of `Prelude` becomes ambiguous, since `Prelude` is defined by both `base` and `codeworld-base`.  This can be fixed by adding a language pragma:
```
{-# LANGUAGE NoImplicitPrelude #-}
```
3. Now, though, `Prelude` is no longer implicitly imported, so one needs to import it manually.
```
import "codeworld-base" Prelude
```
4. Finally, now that modules from `base` are imported, one must deal with the fact that their functions are typically curried, unlike CodeWorld's educational dialect.  It's still possible to use a curried function, but since the educational dialect requires parentheses, it must be written like this: `foldl1'(arg1)(arg2)`.

That's a lot of jibberish, but it works in the end.  I could see doing this to set up a framework, which would then be exposed to students to use in the standard CodeWorld conventions (for example, using import-by-hash).  It definitely wouldn't be something for students to use directly.

**Comment by cdsmith** [comment]
Leaving this issue open for a while in case there are things that can be done to make this easier.  I cannot think of anything.

**Comment by cdsmith** [comment]
Not going to do anything here
