### ISSUE TITLE
Web browser not launched

### ISSUE THREAD

**Issue by Carina-Cai** [google/codeworld#1483]
After the installation, I tried to run the server while no browser was launched.
<img width="787" alt="Screen Shot 2021-01-17 at 11 38 27 pm" src="https://user-images.githubusercontent.com/76047281/104872566-4f9a0500-59a2-11eb-9646-af6346b1f666.png">
Before I ran it I killed all processes that were running on port 80 already. What could be the possible reasons?
Any help will be appreciated.

**Comment by cdsmith** [comment]
This looks like it's working.  What happens when you point a web browser to http://localhost now?  The run.sh script starts a web server, but you need to start the web browser and point it to the server yourself.

It does look like you're not able to start codeworld-game-server because another process is already listening on that port.  To debug this, you would need to check which process is already listening there.  Try `fuser -v -n tcp 9160` (unless you changed the port) to find out which process that is.  Without the game server running, you should be able to do most things in CodeWorld, but multiplayer games (the `groupActivityOf` entry point) won't work.

**Comment by Carina-Cai** [comment]
It doesn't seem like working, and nothing was returned when I tried to find out the processes that were listening on port 9160. 
<img width="1508" alt="Screen Shot 2021-01-19 at 1 53 02 pm" src="https://user-images.githubusercontent.com/76047281/104999162-7f1f3f00-5a80-11eb-8e21-61ad539f03fc.png">
<img width="477" alt="Screen Shot 2021-01-19 at 1 53 15 pm" src="https://user-images.githubusercontent.com/76047281/104999268-b0980a80-5a80-11eb-8f76-289e704bdf35.png">
Is there any other possible reasons?

**Comment by cdsmith** [comment]
Notice that the output of run.sh indicates you have codeworld listening on port 80, NOT port 8080.  You've pointed your web browser to port 8080.  That's not going to work.

**Comment by Carina-Cai** [comment]
Actually I redirected port 80 to port 8080 and that’s the reason why I had my browser pointed there. I tried 80 as well but got the same result. Sorry I am just really confused and tried to set things right.

**Comment by cdsmith** [comment]
I don't know what else this could be.  There are a lot of pieces here that I can't see, and I am guessing the problem is in one of those.

Since your screenshot of the run script says that codeworld-server is listening on port 80, can you try that?  If that works, then you know the problem is in whatever it is you've set up to redirect port 8080.

**Comment by Carina-Cai** [comment]
I tried rebuilding it and changed the run script so that the server listens on port 8080. Now it is working fine. Thank you so much for helping!
