### ISSUE TITLE
"lettering" of certain numerical values seems to cause black screen

### ISSUE THREAD

**Issue by gjduff** [google/codeworld#1513]
**Shared Program**: https://code.world/haskell#PzW7_noa9MQgZA9c31OjP6Q

**Description**

In Chrome browser/windows 10,
the shared program above causes a black screen.

Further details:
1)  comment out line 22 - works again.

2) uncomment line 42
    comment out line 43, 44   - works again

**Comment by cdsmith** [comment]
The problem is on line 44.  You wrote `seconds = if secondsRaw >= 60 then 0 else seconds`, but that's an infinite loop.  You meant `seconds = if secondsRaw >= 60 then 0 else secondsRaw`.  Commenting out line 22 fixes the problem only because `seconds` (which is bottom) is never forced, so the infinite loop isn't evaluated because of lazy evaluation.

As far as CodeWorld is concerned, I can see maybe setting a time limit of some sort on evaluating the picture to display, and displaying a warning in the console if the picture loops like that.  But ultimately this was a bug in the program preventing it from drawing the screen because of the infinite loop.

**Comment by gjduff** [comment]
Oh, I see.
Sorry about that - the black screen threw me off a bit.

I got burned by the line looking OK for a non-functional language, plus lazy evaluation.
