### ISSUE TITLE
WURFL can no longer be loaded, preventing initialization of CodeWorld

### ISSUE THREAD

**Issue by ByteEater-pl** [google/codeworld#1641]
The `textarea` for code is small and the Run button has no visible effect. Probable cause is logged in the console:
>Loading failed for the <script> with source “https://wurfl.io/wurfl.js”. [code.world:182:62](https://code.world/)
>Uncaught (in promise) ReferenceError: WURFL is not defined
>    initCodeworld https://code.world/js/codeworld.js:337
>    init https://code.world/js/codeworld.js:248
>[codeworld.js:337:22](https://code.world/js/codeworld.js)

**Comment by josephcsible** [comment]
The bug is here: https://github.com/google/codeworld/blame/a553dabfe0c739f48619d372aaedffddbb39553f/web/js/codeworld.js#L337
The `!WURFL` side of that check is intended to keep things working if WURFL doesn't load, but since that script is getting loaded in strict mode, accessing an undeclared variable that way is an error rather than just giving `undefined`.

**Comment by josephcsible** [comment]
#1644
