### ISSUE TITLE
Consider making blocks look more like the underlying language

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#184]
This is speculation more than a feature request.  I'm interested in thoughts on the matter.

The goal of the original Blockly project was to create a stand-alone block-based environment to teach beginning computer programming, and they made some design choices to support that goal.  Among them: name blocks with clear English language words and grammar.

The goals of CodeWorld are a bit different.  Among these goals: get students familiar and comfortable with working with mathematical notation, and keep the bridge open to graduate from the block UI to the text UI for more advanced projects.  I'm coming to believe that this difference in goals should be reflected in the UI.  Perhaps the blocks should:

* consistently use the same names as CodeWorld: "drawingOf" rather than "Drawing Of", for example.
* have visible parentheses, commas, and other syntax.
* always use the "inline" style of embedding sub-blocks rather than attaching them on the side.

This might look a little less familiar to beginning students, it's true.  It might accomplish more of the goals of the project.

Discussion welcome.  I'm not even sure what I personally think.

**Comment by stefan-j** [comment]
I'm also for making this closer to the underlying language. A block based interface is good for getting students motivated and familiar with the concepts, but such an interface can't be used indefinitely. Educational block based languages are used temporarily as a means to introduce computer programming.
 
The end point should be to get students familiar enough to be able to move on to a text based environment, and having functions show their CodeWorld names will make the transition easier. 

On the other side it might also be important to get students familiar with programming in a friendly and intuitive manner, so that they understand programming concepts and think logically about programs. This might involve making the interface as easy as possible to use and disregarding some notational consistency.

Some of Blockly Games' [later examples](https://blockly-games.appspot.com/pond-duck) have blocks that represent their JavaScript almost identically, with parentheses and commas and so on. 
Too much such characters looks like line noise, and I'm not sure how much of that would be remembered if the user does not have to type it himself.

Probably some compromise is needed to make the interface as friendly as possible and make it easy to move on to text based programming later.

I don't really know how to weigh these as I don't have much experience teaching programming. Just my 2 cents.

**Comment by cdsmith** [comment]
I like the change to use CodeWorld function names.

Further things to think about here:

1. Add language syntax, such as parentheses and commas, to the blocks.
2. Render the "helper" text that labels parameters in a smaller size and/or different color, to distinguish it from the actual program.  Or perhaps move it to the tooltip.

**Comment by cdsmith** [comment]
Would still be great to add the language syntax (parens and commas) to the blocks.

**Comment by cdsmith** [comment]
Thanks for the updates on this.  A few places that could still use the change:

- Add parentheses and commas to user-defined function blocks (but remove them for the first-class representation?  Is that possible?)
- Add parentheses and commas in the let block, when there are parameters.
- Add an equal sign to the let block.
- Add the `data` keyword when defining new types.
- Add parentheses and commas for constructors and their parameters, in `data` blocks, `case` blocks, and constructor blocks.
