### ISSUE TITLE
A way of viewing just the result

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#255]
The links that CodeWorld present give access to the code. This means that if I want to create an assignment of “recreate this drawing”, I cannot simply link to the output as rendered on CodeWorld.

I think I could use a second, different share URL that 
 * Links to a page that *only* shows the Canvas, with start and stop buttons.
 * Has a different hash (either different algorithm, or some salt added), so that the normal URL cannot 
   be reproduced from it.

(This is under the assumptions that students who can reverse engineer the Haskell code from the output of GHCJS deserve not having to do the homework…)

I guess I should set up codeworld locally so that I can contribute such obscure features :-)

**Comment by cdsmith** [comment]
I'm happy to have this feature in the main site.  You can get everything except a new hash using https://code.world/run.html?hash=XXX as the URL.  In fact, the Share button used to provide that URL; I made the current change to encourage sharing source code in the educational environment.

The missing step would be to encrypt the hash.  So that /runJS?enchash=XXX would unencrypt the hash before the compile and serving steps, and run.html would plumb encrypted hashes through.  This is all fine.  It would need a new encryption key to be generated per server, which is a deployment hassle.  So far, I've been handling things like that with local files and .gitignore (e.g., see handling of clientId.txt); but something like https://hackage.haskell.org/package/keystore doesn't seem too awful if we started accumulating these things.

**Comment by cdsmith** [comment]
The last question is how to get the URL, I suppose.  Perhaps the Share button should offer options to share the code, or just the result.

**Comment by alphalambda** [comment]
A simple solution I have been using is to use "Save As Image" on the canvas window, and then put the image somewhere so that students can see the output.

**Comment by cdsmith** [comment]
@alphalambda Right, I assume this request has to do with animation, simulation, and interaction modes.

@nomeata One part of the initial request that I missed was having Run and Stop buttons outside of the code environment.  Honestly, I'd try to avoid that, both because it's likely to be annoying to implement, and because I feel like in principal when you drop the CodeWorld environment, you should lose all the CodeWorld design elements (colors, etc.).  There are already much more neutral pause/restart buttons automatically added to any animations and simulations, which should do this job just fine.  When it comes to interactions, I'd encourage you to just design them so that they are easy enough to restart anyway.

**Comment by nomeata** [comment]
You don’t need to trouble yourself with encryption, a fixed salt should suffice.

I assume that you are keeping an index of hashes to stored code, i.e. a mapping of `md5(code) → code`. A second mapping of `md5("salt"++code) → code`, and using that for the `chash` parameter,  should suffice, because there is no way of getting `md5(code)` from `md5("salt"++code)`.

**Comment by nomeata** [comment]
Also, https://code.world/haskell/run.html seems to behave different than https://code.world/run.html.

**Comment by cdsmith** [comment]
@nomeata You want /run.html.  The fact that /haskell/run.html doesn't 404 is a bug.

**Comment by nomeata** [comment]
> A simple solution I have been using is to use "Save As Image" on the canvas window, and then put the image somewhere so that students can see the output.

As @cdsmith points out, this misses animation etc. And even for drawings, it turns them into pixel graphis. And I don’t like pixel graphics to the point that I once hacked gtk to create [vector screenshots](https://www.joachim-breitner.de/blog/494-Better_PDF_screenshots_with_gtk_3), and abused the print-to-PDF feature to include PDF “screenshots” of webpages in [an acdemic paper](http://pp.ipd.kit.edu/uploads/publikationen/breitner16incredible.pdf):

**Comment by nomeata** [comment]
>  @nomeata You want /run.html. The fact that /haskell/run.html doesn't 404 is a bug.

Does `/run.html` also work for code created in the Haskell instance? I have <https://code.world/haskell#Pqls0NfwUQVlOsJiW88ovgg> but not <https://code.world/run.html?hash=Pqls0NfwUQVlOsJiW88ovgg> and indeed <https://code.world/runJS?hash=Pqls0NfwUQVlOsJiW88ovgg> says 
> data/codeworld/user/Pql/Pqls0NfwUQVlOsJiW88ovgg.hs: openBinaryFile: does not exist (No such file or directory)

**Comment by cdsmith** [comment]
@nomeata Sorry, I updated my earlier reply.  You need /run.html?hash=XXX&mode=haskell

except that apparently I broke it, too, by making run.html look at its parent frame for the build mode.  I'll fix that now.

**Comment by cdsmith** [comment]
Okay, now the URL with mode=haskell should work

**Comment by cdsmith** [comment]
Regarding projects by salt: seems fair.  The storage right now is pretty trivial, though.  There is no index: just filenames on disk.  I would need to create such an index for this feature.  But you're right that this is better than needing a secret encryption key.  Thanks!  I'll look into this now.

**Comment by nomeata** [comment]
`run.html` works great in an iframe. I have added them to the lecture notes already (where there is no secrecy requirement), check it out: http://www.seas.upenn.edu/~cis194/fall16/lectures/01-intro.html

**Comment by nomeata** [comment]
>  The storage right now is pretty trivial, though. There is no index: just filenames on disk. I would need to create such an index for this feature. But you're right that this is better than needing a secret encryption key.

If you are already using the file system, then it can just as well serve as the index: A second directory, with one file per “secret” hash, which is a symbolic link to the real file.

**Comment by cdsmith** [comment]
Sorry this is going so slowly.  I'm doing it in spare moments here and there.  Getting there, though!

**Comment by nomeata** [comment]
Class starts in 13 days, so no sweat yet :-)

**Comment by cdsmith** [comment]
https://code.world/run.html?mode=codeworld&dhash=DjjENsL0uiKbwUtMOOgLGAg

**Comment by cdsmith** [comment]
Should work now!  You can use the Share button, and use the button on the dialog to switch to sharing without source code.  Let me know if this works for you.

**Comment by nomeata** [comment]
Works great! You can see it in action on <http://www.seas.upenn.edu/~cis194/fall16/hw/01-intro.html>.
