### ISSUE TITLE
Parameter blocks keep old type even after changes

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#312]
Start with this: https://code.world/blocks#PwTxyVGuDi1cNBOoh8VzEiw

Disconnect the pair from the right-hand side of the MousePress event.  The case block's connectors, and the template `state` parameter block, all correctly generalize to be polymorphic.  However, the already existing instances of the `state` parameter keep their shape as pairs.

**Comment by stefan-j** [comment]
The underlying problem is that not all blocks are redrawn. Currently only the affected connected/disconnected blocks and their parents are rendered after the inference (it's slow redrawing everything)

This can be verified by running
```
Blockly.getMainWorkspace().getAllBlocks().forEach(b => b.render())
```
which forces blocks to be redrawned. 

I think I need to either look at redrawing everything that had a type change or redrawing blocks that have not already been redrawn (render redraws the block and all its parents, even if they have recently been rendered)

Possibly related: #308
