### ISSUE TITLE
No type inference in disabled blocks

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#316]
![disab](https://cloud.githubusercontent.com/assets/544744/18329865/70eaec5a-750a-11e6-9283-01009fbdce1f.png)

This is a pair block with two numbers in it.  Because it's disconnected, type inference doesn't run, and it appears broken.  We should be doing some kind of best effort inference even on disconnected blocks.

**Comment by stefan-j** [comment]
I disabled type inference previously on disabled blocks to hopefully improve performance. However since I did a large overhaul on the performance issues it should be a non-factor.
Another note, I also skipped checking top-level blocks which have an output type.


I have removed these two checks and type inference should now work on disabled blocks. in my [Blockly fork](https://github.com/stefan-j/blockly/commit/cf60fa584d1032eac7c7fccd301e07c8796c2657).

**Comment by cdsmith** [comment]
Thanks!
