### ISSUE TITLE
Multiplayer game mode

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#372]
Chris good me hooked on the idea of getting some multiplayer support added at HackPhi this year. This issue tracks the progress.

**Comment by cdsmith** [comment]
Related: #92

**Comment by cdsmith** [comment]
To summarize status here: @nomeata built a really awesome demo at Hac Phi, with this API:

    gameOf ::
        Int ->  -- Number of players
        state ->  -- State, shared between all players
        (Double -> state -> state) ->  -- Step function
        (Int -> Event -> state -> state) ->  -- Event function, where Int is the player id
        (Int -> state -> Picture) ->  -- Picture function, where Int is the player id
        IO ()

The idea is to send all events to a websocket-based server, and have it return a fixed canonical event stream to all clients.  Since all clients are running the same code with the same initial state, and the same stream of events, they should each maintain the same game state, without ever serializing a state value over the network.  So, in particular, the state type may still contain infinite lists, functions, etc.  That's awesome!

As an optimization, the thought was that it should be possible for some events to be played locally on the client for responsiveness, so long as the client is willing to rewind and replay them when the canonical version is received from the server.

The time step is an interesting problem.  It's not appealing to pass all time steps through the server, and it's also not appealing to try to canonicalize 60 fps of timestamps.  So the thought here was that times should just be attached to events.  In between a gap in events, clients should process time events at a fixed canonical rate of a few frames per second.  For the sake of smoother animation, clients can use smaller timestamps to draw intermediate frames; but, they should regularly revert back to the canonical values at each canonical time step.

**Comment by cdsmith** [comment]
One open question is what we do with IO that precedes (or is concurrent with) the game.  This can be overcome with games using the CodeWorld modified Prelude, since there is no I/O outside of the entry point.  (Actually, that's not 100% true.  Simulations and interactions are passed an infinite list of random numbers that are generated by lazy I/O; but these could be generated consistently instead in game mode - for example, using a game instance ID for a seed.  So it's manageable, at least.)

But using http://code.world/haskell, it's quite possible to do something like:

    main = do
        c <- newChan
        forkIO (producer c)
        gameOf 2 (buildState c) ...

And now there's active I/O that can insert arbitrary values into the computation, causing the states to diverge.

One answer is "then don't do that!"  But it's less than satisfying.  And it means that users of the Haskell-mode game API need some other solution for how to generate random numbers...

**Comment by nomeata** [comment]
Good point. Nothing springs to mind immediately. Some initial state description, serializable somehow, sent by player 1 to all others? But that’s not going to be a pretty API.

For now, it’s “don’t do that”.

**Comment by cdsmith** [comment]
gameOf :: Int -> StaticPtr state -> ...

https://ghc.haskell.org/trac/ghc/wiki/StaticPointers

:)

**Comment by nomeata** [comment]
That doesn’t really help, does it? If it is a static pointer, it can only refer to static things. I It would help if the initial player makes a random, `IO`-driven choice between a finite number of static initial states, to transfer this choice over the wire.

**Comment by cdsmith** [comment]
I suppose there are two problems.  StaticPtr was meant to help with enforcing the restriction that the initial state doesn't depend on anything process-specific.  The serialization functionality can be ignored!

StaticPtr doesn't help when you *want* different state, though.  We could solve the random number case like this:

    gameOf ::
        Int ->
        StaticPtr (StdGen -> state) ->
        (Double -> state -> state) ->
        (PlayerID -> Event -> state -> state) ->
        IO ()

For the CodeWorld mode, I could drop the StaticPtr because the lack of monad operators and lazy I/O already prevents the use of inconsistent values.  (This isn't *really* true, but it's true if you don't use the GHC_OPTIONS pragma to add new packages.)  And turn the StdGen into a lazy infinite list to keep the API consistent.

For arbitrary I/O, I just don't think it's possible.  You need purity for the idea to work at all!

**Comment by nomeata** [comment]
> StaticPtr was meant to help with enforcing the restriction that the initial state doesn't depend on anything process-specific.

Ah, I see. Clever! But then you need to `StaticPtr` also the two handler functions! (The draw function is fine, that may diverge).

**Comment by cdsmith** [comment]
Right!  So, to summarize, I think we want something like this.  In `codeworld-api`:

    type PlayerID = Int

    unsafeGameOf ::
        Int ->
        (StdGen -> state) ->
        (Double -> state -> state) ->
        (PlayerID -> Event -> state -> state) ->
        (PlayerID -> state -> Picture) ->
        IO ()

    gameOf ::
        Int ->
        StaticPtr (StdGen -> state) ->
        StaticPtr (Double -> state -> state) ->
        StaticPtr (PlayerID -> Event -> state -> state) ->
        (PlayerID -> state -> Picture) ->
        IO ()
    gameOf players initial step event picture =
        unsafeGameOf players (deRefStaticPtr initial) (deRefStaticPtr step)
                     (deRefStaticPtr event) picture

And in `codeworld-base`:

    gameOf ::
        Number ->
        ([Number] -> state) ->
        ((state, Number) -> state) ->
        ((state, Event, Number) -> state)
        ((state, Number)  -> Picture)
        -> Program
    gameOf players initial step event picture = CW.unsafeGameOf
        (floor players)
        (\stdgen -> initial (randomsFromSeed stdgen))
        (\dt state -> step (state, realToFrac dt))
        (\player e state -> event (state, e, fromIntegral player))
        (\player state -> picture (state, fromIntegral player))

**Comment by nomeata** [comment]
If the additional safety is worth the additional complexity for the user? But as long as it does not affect the simpler entry points (`drawingOf`) it is probably fine.

**Comment by cdsmith** [comment]
I don't know.  It's interesting, at the very least, to understand why the static pointers are necessary for correctness.  Maybe relying on a language extension isn't the best practical trade, though.  The good news is that it's trivial to provide both versions and try them out in practice.

**Comment by nomeata** [comment]
Given that it only affects the games, by the tume a student is approaching that API, it is reasonable to discuss these things. So :thumbsup:

**Comment by cdsmith** [comment]
Turns out we do actually need to send the StaticPtr over the network for soundness.  Otherwise, we'd be vulnerable to a program like:

    main = do
        k <- randomRIO (0, 1)
        let initial | k == 0    = static a
                    | otherwise = static b
        gameOf 2 initial step event picture

So one idea here is that the game server should be extended to hold a binary blob associated to each session, which is propagated to clients when they join.  In `gameOf`, this would be the serialization of CloudHaskell static pointers, and client can either verify the parameters match, or just ignore its parameters and adopt those from the server.  For unsafeGameOf, we can simply leave the blob empty, and omit that check.

I should verify that StaticPtr even works with GHCJS.

**Comment by nomeata** [comment]
> The game server should be extended to hold a binary blob associated to each session, which is propagated to clients when they join.

It would be sufficient to change the protocol so that the `Sent` event is not broadcast by the server, but rather a client message that is sent from player 0, and then timestamped and broadcast to all clients. This message can then have arbitrary payload, including a `StaticPtrName`.

**Comment by nomeata** [comment]
I have prototyped the prediction event handling in 1b5781e. Is this mostly the algorithm that we thought about at last weekend, or did you have something slightly different in mind?

**Comment by cdsmith** [comment]
Yep, that looks perfect!

The one concern I initially had was this: if there are no events, do we want to allow the committed and local states to differ by arbitrary long delays?  Two possible problems with that.  First, when you do receive a server event, there's a large amount of stepping to replay in one frame.  Second, it will be very common for games in CodeWorld to lazily consume infinite lists (e.g., my custom Prelude offers a lazy list of random numbers when building the initial state), so retaining a state too far in the past risks blowing up the heap usage.

BUT, that doesn't require any changes here, since `id` is a perfectly good value of type `Event s`.  So that works out nicely!

**Comment by cdsmith** [comment]
@nomeata I've got a valid merge with master locally that works on the remote server.  I've added a WARNING pragma to gameOf to note that the API is still experimental.  I think I'll push that so we have more fun toys to play with and to avoid more merging issues?

**Comment by nomeata** [comment]
> if there are no events, do we want to allow the committed and local states to differ by arbitrary long delays? 

Good point. That could easily be fixed by the server sending a periodic Ping event (is that what you mean with the `id` event)? A ping might be a good thing anyways, to detect broken connections soon.

**Comment by nomeata** [comment]
>  I think I'll push that so we have more fun toys to play with and to avoid more merging issues?

Fine with me, of course! Did you add code that communicates the websocket URL to the driver?

**Comment by cdsmith** [comment]
For now, I'm running the websocket server on the same host as the server on your chosen per number, and using window.location to build the URL.  We may want to change that, but it seems like an implementation detail, given that we can force all clients to recompile at any time.

**Comment by nomeata** [comment]
> using window.location to build the URL
That works, good!

**Comment by cdsmith** [comment]
JavaScript exception: SecurityError:
        Failed to construct 'WebSocket':
        An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

However, this works: http://code.world:8080/haskell#PnZljFAMjM-JZFOGxWxpC3Q

I just need to configure nginx to proxy another port with SSL.  I can figure that out tonight.

**Comment by nomeata** [comment]
Here is a game to play around with: http://code.world:8080/haskell#PCdDhIx0MFZ5dIOg7_QkLCw

Unfortunately, it does seem to drop some events.

**Comment by nomeata** [comment]
Do we care about cheating clients? If not, it might make sense to have the clients produce the time stamps for their events, so that the relative time difference between two events from one player is stable (this might be important for a 180° turn in a snake game). This would imply that the server only broadcasts the events, but the order is defined via the time stamps. This implies that the client need to be able to in retrospect add other player’s events. So in order to know how far back the events have to be stored, every client would have to send out regular pings. (I’m just throwing this out here, I’m not sure if this is any better.)

**Comment by cdsmith** [comment]
I'll go ahead and say that we do not care about cheating clients.  IMO, that's a problem we can't reasonably solve without complicating the API.  (For example, you may in many cases have to conceal part of the state from the client.)

By the way, this may not work for the next few minutes.  I'm fixing it.  Please be patient. :)

**Comment by cdsmith** [comment]
> Here is a game to play around with: http://code.world:8080/haskell#PCdDhIx0MFZ5dIOg7_QkLCw

Nice... but it doesn't work.  The very first game ended up with each of us believing that the other had already lost.  I suppose that's because we each tried to apply the events at different times.

**Comment by nomeata** [comment]
Right. Using the `Prediction` model should fix it.

**Comment by cdsmith** [comment]
Yep, I'll take a shot at integrating that now.  It looks straightforward since you wrote the logic already!

**Comment by cdsmith** [comment]
> That could easily be fixed by the server sending a periodic Ping event (is that what you mean with the id event)? A ping might be a good thing anyways, to detect broken connections soon.

Yes, that's what I meant.  Handling a ping (with a timestamp `t`) is just `serverEvent step rate False t id`

**Comment by alphalambda** [comment]
Sorry to jump into the middle of this thread. I have been using CodeWorld this semester in a
Computational Physics course to illustrate solution methods for simple ODE's and compare
performance of Euler vs Runge-Kutta methods.

Now, we are moving to numeric linear algebra, and I was thinking about how cool it would be to
illustrate parallel matrix algorithms by having different groups of students work on different
blocks of a matrix, and then communicate their partial results to a central node that sends
back the matrix to everybody to visualize it. Sort of an el-cheapo MPI, but with pedagogy
as a goal rather than efficiency.

The events in this case would not be Keyboard/Mouse, but "Computation Ready" messages
with a payload. So, I wondered if something like this could be built on top of the new multiplayer mode.

Is this the right venue to discuss this or should I use another one?

Thanks,
Fernando Alegre

**Comment by nomeata** [comment]
> Is this the right venue to discuss this or should I use another one?

I think that’s definitely another thread. The point of this one is to avoid the programmer to think about concurrency or network, not teach it :-)

**Comment by cdsmith** [comment]
@alphalambda First of all, let me say that sounds really awesome.  If you have any experiences you can share about the class, I'd love to hear them, and there may be more people interested at https://groups.google.com//forum/#!forum/codeworld-discuss

As far as your idea: if this works, it should be pretty universal as far as collaborative user experiences goes.  The `gameOf` is a bit of a misnomer here, and nothing is specific to games; perhaps it should be called `collaborationOf` instead.  You can't use this to actually parallelize the computation itself; but you could assign each students a range of a matrix to work on.  Take a look at this!  https://code.world/haskell#P7p5UtSK3ik3PhZiNPzL7cw

**Comment by cdsmith** [comment]
Okay, my last response didn't make much sense.  For some reason, I got it in my head you were asking about using a collaborative UI to do the concurrency by hand.  But if that were the case, you should just use Google Docs instead. :)

**Comment by cdsmith** [comment]
The initial implementation of this feature is working!  This bug has gotten very long, so I split the various remaining concerns out to different issues, where they can be tackled individually.  Closing this in favor of:

Remaining issues:
* #374
* #375
* #376
* #377
* #378
* #379

**Comment by alphalambda** [comment]
> But if that were the case, you should just use Google Docs instead. :)

That's correct. I am wondering whether it would be possible for the clients
to send and receive user-defined events so that different nodes can compute
different parts of a solution and broadcast their part to the other nodes.

It would probably be enough for most cases that the custom event payload were
a list of numbers or a string, to avoid having to serialize arbitrary types.

**Comment by cdsmith** [comment]
I'm not opposed to having such an entry point.  I think @nomeata is right that it's a different goal, because the entire point here is to insulate the user from the details of communication between clients.  But it's certainly possible to reuse the same message relay server that he's built for this.

Can you file a new issue and see about proposing an API that does what you want?  I think a generic type like `Text` or `ByteString` for the messages could make sense.

**Comment by nomeata** [comment]
Until I have a better place to keep a link to the examle snake game: Here it is, adjusted to the latest API: http://code.world:8080/haskell#PfEg7YgQyWL94u8YJ7XCaMw
