### ISSUE TITLE
Run mode needs to show URL to join

### ISSUE THREAD

**Issue by nomeata** [google/codeworld#381]
Once I have programmed a game, I want to share a link that allows people to start their own games, without going through the editor view. That is, basically, the run view. But currently, it does not show the link (because it tries to call a function outside).

Maybe it would be nicer to integrate the showing of the „Share this URL“ into the canvas (or at least the frame, overlying the canvas). Maybe with a button that copies the URL to the clipboard.

Also, the waiting for other players could be visualized. E.g. circles that are filled until all circles are filled.

(This is somewhat rambly phrased. Do you know what I mean?)

**Comment by cdsmith** [comment]
Copying to the clipboard without a user action is tricky, because of browser security policies.  Looks like there's an open-source library called clipboard.js that abstracts over the many ways of doing it, so maybe that makes it feasible now.

**Comment by nomeata** [comment]
It could still be an HTML-based dialogue with an entry field. It just needs to be contained by the `run.html` window, not the `env.html` window.

**Comment by cdsmith** [comment]
I'm switching now to sharing by four-letter codes.  This means typing game codes in the canvas itself, rather than using a dialog.  That will fix this problem.

The new workflow will be:

1. Share the URL for your project.  You can choose whether to include the source code or not.
2. All players run the game on their own.
3. One player chooses to start a new game, and communicates the 4-letter code to the others.
4. Other players type in the code.

**Comment by nomeata** [comment]
So upon disconnection, you again get the choice of starting a new game, or entering codes? That sounds nice!

**Comment by cdsmith** [comment]
Closing this as a duplicate.
