### ISSUE TITLE
Installation shouldn't repeat steps unnecessarily

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#435]
The install script currently downloads and installs GHC, Cabal, node.js, etc. every time.  Instead, it should look at the currently installed versions, if any, and only replace them if they don't exist or the version has changed.

**Comment by venkat24** [comment]
If the user has a version different from what we require, should we remove and replace the version? What if they have a higher version?

**Comment by cdsmith** [comment]
Since everything is installed in the build subdirectory and used only for this project, I think it's better to be aggressive, and reinstall anything that we know would differ from what we'd install now.

Are you planning to work on this?

**Comment by venkat24** [comment]
Yes, I'm planning to work on this.

>  it should look at the currently installed versions, if any, and only replace them if they don't exist or the version has changed.

This refers to global installations right? So essentially, we just need to check if there's an existing installation. I'll modify `install.sh` accordingly.

**Comment by cdsmith** [comment]
You know, the only fixed hope I have for this is that running re-running install.sh a second time shouldn't repeat work when nothing has changed.  Beyond that, I'm really up for whatever others find most convenient.

An idea that was floated to me recently was to switch to Nix-based installation.  That seems like it could offer a great combination of benefits.  But I'm not particularly informed about Nix.

**Comment by wisn** [comment]
Recently, I've installed CodeWorld in my Antergos Linux which use `pacman` as the package manager. Since `pacman` didn't listed on `install.sh`, some dependencies are missing and broke the installation process. As you mention that installation always repeat from the beginning. So, for preventing it, I created a checkpoints. "Which step that failure?". After identify the step, I commented out the finished step. Yeah, it's now finish and I can run CodeWorld.

My point for this is we may creates a checkpoint with a `hidden file` as the identifier.  We may placed the `hidden file` in `build` directory.

```
...
- build
---- .step1
---- .step2
// and so on
...
```

And, creates an if-conditional for checks whether the `hidden file` step is exist or not. If it's exist, the step finished. Otherwise, repeat the step.

```
if [ ! -f $BUILD/.step1 ]; then
    # do this step
fi
```

It's my "ugly" but it's works fine.

**Comment by ShengChen** [comment]
In Ubuntu 16.04, the program node needs to be installed with nodejs-legacy. I got weird error messages without manually calling the following before ./install.sh
    sudo apt install nodejs-legacy

**Comment by cdsmith** [comment]
@ShengChen I just built from a fresh Ubuntu 16.04 virtual machine, and didn't see any problem.  You shouldn't need to install nodejs-legacy, since node.js 7.x is installed by the install.sh script.

If this is still a problem for you, any chance you can open a new bug for it, and include the error message?

**Comment by pvdbrand** [comment]
On a fresh install of Xubuntu 16.04, I needed to install npm (sudo apt-get install npm) as well. I did install nodejs-legacy before running install.sh, but I don't know whether that was actually needed.
