### ISSUE TITLE
Add TextEntry Event constructor for logical text

### ISSUE THREAD

**Issue by niole** [google/codeworld#460]
I think that the keypress functionality should be extended. Certain keys are not represented.

Repro:
* use KeyPress
* type some letters
* notice how all of them are always uppercase
* try to type a colon, notice that you can only ever type a semi colon

What is the rationale behind this?

**Comment by cdsmith** [comment]
The KeyPress and KeyRelease events currently receive physical keys, not characters.  So composite actions, like holding shift and such, don't change the name given to each key.  This limits what you can do, but it's not clear to me what should have been done instead.

I'm definitely willing to consider alternatives, but a first step would be a clear specification of a desired behavior that doesn't make event handling more complex.  There will also be a tricky backwards compatibility issue here.

**Comment by niole** [comment]
Is this library rendering key types based on the key press event from
javascript? If it is, diversifying what a KeyPress is could be rather
straightforward.

**Comment by cdsmith** [comment]
My concern isn't about how to implement it.  Rather, I'm not sure what the desired API is.  I suppose what we want is probably very close to the JavaScript "key" property: a character when applicable, but a logical string when not.

This leaves us with the problem that half of existing student games will break, because they are comparing the key with uppercase letters.

**Comment by niole** [comment]
The question of the desired API is the primary reason why I'm asking about
the reasoning behind the current implementation. I'm personally interested
in implementing updates to KeyPress, but it may not be desirable for the
users.

**Comment by cdsmith** [comment]
The reasoning behind the current system was to make it easy for students to write simple games where they just needed to react to a few keys like W, A, S, D to control a character or something.  I didn't anticipate their wanting to type text.  Now, particularly with collaborations, there's a stronger case for wanting to let users type text.

I think the most promising change would be to use an approach like before.  That is:

* Typing the "A" key gives `KeyPress("a")` followed by `KeyRelease("a")`.  (Currently, those would be capitals.)
* Holding Shift while typing "A" would be `KeyPress("Shift")`, `KeyPress("A")`, `KeyRelease("A")`, `KeyRelease("Shift")`.  (This is the same as now.)
* Typing "." gives: `KeyPress(".")`, then `KeyRelease(".")` (same as today)
* Holding Shift while typing "." gives `KeyPress("Shift")`, `KeyPress(">")`, `KeyRelease(">")`, `KeyRelease("Shift")`.  (Currently, the ">" character would be delivered as a ".")

Here's a tricky case: `KeyPress("Shift")`, `KeyPress("A")`, `KeyRelease("Shift")`, `KeyRelease(???)` When the "A" key is released, do you expect to see "A", so that the KeyRelease event matches the KeyPress?  Or "a", since shift is no longer held during the release.

Here's an even trickier case: the user holds "A" long enough to auto-repeat, and releases "Shift" partway through. `KeyPress("Shift")`, `KeyPress("A")`, `KeyPress("A")`, `KeyPress("A")`, `KeyRelease("Shift")`, ???  Do we start delivering lower-case "a" events for further auto-repeats?  Deliver a KeyRelease for the "A"?

There's one more possibility, which may be better for backward compatibility.  In addition to `KeyPress` and `KeyRelease`, add a new event type that's something like `TextEntry`, which delivers only interpreted text that has been typed.  A chat program or something could respond to that, and deliberately ignore the lower level `KeyPress` events.

**Comment by niole** [comment]
I have to look at the source code to understand why determining whether a letter is capital or not might require such an involved process.

Is the output of each key press not determined by the `keyCode` that is attached to the JavaScript event? Is it literally based off of what keys on your keyboard are pressed? If it were based on the JavaScript key press event, one can look at the `keyCode` number and map it to the corresponding text or one could look at the `key` attribute, which has the text content that that key press corresponds to. If the key press is a combination of `shift` and `a`, `key` will correspond to `A`.

There is a caveat here, however. Keys that don't produce a key value (F1, F2, ...) do not trigger key press events.

**Comment by cdsmith** [comment]
It is looking at `keyCode` and converting that to a string.  It is not looking at `key`.  We could definitely change it to look at `key` instead (with some backward compatibility hacks), but this would break most existing student games, which expect the same value for the same key.

**Comment by niole** [comment]
Yeah, I understand there would be backwards compatibility issues. Those could be circumvented with a new data type, like you mentioned. `TextEntry` is a fine name, although I wish `KeyPress` could be used as it hints at the underlying JS event system. It's also reasonable to say that this is not within the scope of codeworld-api.

**Comment by cdsmith** [comment]
Hmm.  I'm actively opposed to making decisions to be consistent with JavaScript, or any other typical programming language.  They almost always end up being the wrong choices, and then I go back and change them later when it becomes clear that they are contributing factors to students giving up on their intuitions.  The list of times I've been down that path is quite long: verbs as function names, measuring distances in pixels, orienting the y axis downward, "string" as a word for text, and so on.

Instead, we should do the simplest thing that makes abstract sense.  However, I'm not sure what that is here.  `TextEntry` works great, but two events firing for the same action is counterintuitive.  And attaching both a text and physical key meaning to the same `KeyPress` event makes the semantics of the event type too complicated.  Right now, my preference is leaning toward `TextEntry`.

**Comment by cdsmith** [comment]
I do think this is worth fixing.  Particularly with collaborations, this is going to be a frequent request.

**Comment by niole** [comment]
I like `TextEntry`, mostly because I can easily see how to add it in and there's the backwards compatibility side. It's not great because it won't pick up all types of key presses, like F keys. Then if a user wants F keys and more flexible text entry capabilities, they will have to listen to `KeyPress` and `TextEntry`, which will sometimes fire at the same time, like you noticed. I'm wondering:
* Will that be confusing? It could add complexity to whatever app uses both data types 
* Should another abstraction be made for key presses that don't have text attached to them?
* Is it good enough to just add `TextEntry` and think about the rest later?

**Comment by cdsmith** [comment]
I think the right thing to do is add a `TextEntry`, and implement the following behavior:

1. Always generate a `KeyPress` event, which acts exactly as it does now.
2. In addition, if and only if KeyboardEvent.key is one character long, *also* generate a `TextEntry` event with that character.

You are right that most applications will need to listen for both TextEntry and KeyPress.  A common pattern will be:

    initial(rs) = ""

    event(txt, TextEntry(ch)) = txt <> ch
    event(txt, KeyPress("Backspace")) = allButLast(txt)
    event(txt, KeyPress("Escape")) = ""

    allButLast("") = ""
    allButLast(txt) = joined(first(characters(txt), numberOfCharacters(txt) - 1))

**Comment by niole** [comment]
Ok! This feels right.  I'm going to take a crack at it

**Comment by niole** [comment]
Looks like `key` is not supported with the Canvas library that codeworld's using and keyCode output is limited. This brings us back to what you were saying earlier about maybe needing to parse the stream of events to know when something is uppercase. I guess that could be done. Either that, or PR the Canvas library (libraries).

**Comment by cdsmith** [comment]
Is this not what you need?  https://github.com/ghcjs/ghcjs-dom/blob/master/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/KeyboardEvent.hs#L112

**Comment by niole** [comment]
That's a possibility part of the time, but because of the conditional imports in `codeworld-api/src/CodeWorld/Driver.hs`, that won't solve the problem completely.

**Comment by cdsmith** [comment]
Ah yes, I'd forgotten about the native Haskell version.

I think it's entirely reasonable to focus on an implementation for the GHCJS path, and leave the native version lagging behind, for now.  The native code path could even neglect to deliver `TextEntry` events at all.  We'd then file a bug to update the native library.  The (eventual) right solution there would be to path http://hackage.haskell.org/package/blank-canvas to do what we need.
