### ISSUE TITLE
codeworld-api does not install with cabal-install

### ISSUE THREAD

**Issue by axman6** [google/codeworld#466]
One of my students ran into a problem where they couldn't install codeworld-api  due to dependency conflicts. He had a fresh install of the latest haskell platform, with a newly deleted `~/.ghc` and `~/.cabal` to make sure it wasn't version conflicts. There appeared to be problems with text, mtl and many other libraries. Sadly I don't have the transcript of the build to share.

It would be good to at least include some version bounds on the packages.

The eventual solution was to install `homebrew` and then `stack` which allows for a coherent set of package versions to be installed, but now I'm responsible for providing specific help to this one student.

**Comment by cdsmith** [comment]
Thanks for the report, and sorry!  I knew I was being lazy with version bounds, but since I originally never intended to distribute anything via Hackage, I didn't bother with it.  Since Joachim added the native package, I should be more vigilant about that.

I've uploaded a new version, which has version bounds for the native impl, and downloads and installs fine from a clean ~/.ghc directory for me.
