### ISSUE TITLE
Moving a program to a folder does not work

### ISSUE THREAD

**Issue by pvdbrand** [google/codeworld#566]
Since several weeks/months, moving a program to a folder does not work anymore.

After opening the program, I clicked Move, and then clicked the folder I want to program to be moved to. However, nothing happens. The program stays where it was and is not moved to the folder.

**Comment by cdsmith** [comment]
Yikes, I forgot about this.  Confirmed it now, though, and I have some time this weekend, so I'll try to get a fix in.

**Comment by cdsmith** [comment]
The problem is that when you select "Move", the  CodeMirror system queues up a 'changes' event, which then triggers updateUI, and immediately aborts the pending move operation.  I'm unsure how this used to work!  Perhaps an older CodeMirror version triggered 'changes' synchronously from setCode.

The right answer is clearly to not make functional changes from updateUI, but this means updating other actions that should cancel a pending move operation.  I'll fix it soon.
