### ISSUE TITLE
Some layers not being transparent

### ISSUE THREAD

**Issue by schteeben95** [google/codeworld#593]
`drawingOf $ (coloured blue $ solidRectangle 1 1) & (translated 5 5 $ coloured red $ solidRectangle 1 1)`

This should draw a blue rectangle and a red rectangle. However, it only draws the red one since commit c2934c2.

I'm using GHC 8.2.2.

**Comment by cdsmith** [comment]
I tried to reproduce this with https://code.world/haskell#PObrABisx22_7fCl-R31TiQ, but wasn't able.

From your report, it seems like you're installing a sa binary build using the plain GHC version that @nomeata set up, rather than using a CodeWorld server and web interface?  If so, it's very likely that the changes by @three were incorrect when GHCJS is not used.  (There are a bunch of `#ifdef`s there, so that's not surprising.)

I can take a better look tonight, but unfortunately I'm having trouble building that because `unix` fails to install with GHC 8.2 on the system I have with me now. :(

**Comment by schteeben95** [comment]
@cdsmith No I didn't use the web interface. In our class we might just revert to using CodeWorld 0.2.1.0 and GHC 8.0.2 for now. Thanks for having a look at it.

**Comment by cdsmith** [comment]
Yes, I can reproduce now using the blank-canvas version.  I'll try to fix this and release a new version tonight.

**Comment by cdsmith** [comment]
This was a rather embarassing bug, but thank you for finding it!  I've now pushed a 0.2.2.0 of codeworld-api to hackage, including the fix.

**Comment by schteeben95** [comment]
Sweet. Cheers!
