### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#601]
Ran ```.build.sh.``` Build was aborted. Running Ubuntu 14.04 i686.

![screenshot_2018-04-24_22-08-13](https://user-images.githubusercontent.com/8516378/39224320-9f656996-47fb-11e8-8d7d-4e416f630616.png)

**Comment by kammitama5** [comment]
I added this line of code 
```
elif /sbin/ldconfig -p | grep -q libgmp.so.6; then
  GHC_ARCH=`uname -m` -i-x86_64-linux-gnu
```
![screenshot_2018-04-24_23-35-18](https://user-images.githubusercontent.com/8516378/39226499-b99a5ab8-4807-11e8-94e7-0b1d9a16092a.png)

and it shows that GHC has been installed, but there is a warning about a syntax error on line 230.

![screenshot_2018-04-24_23-35-41](https://user-images.githubusercontent.com/8516378/39226552-fc8b3c20-4807-11e8-9550-bf1a04ad6965.png)

**Comment by Gabriel439** [comment]
The immediate problem is that the URL you need is not present, specifically this URL:

http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i686-deb8-linux.tar.xz

An easy way to reproduce the failure without rerunning the entire script is to use `wget`:

```bash
$ wget --spider http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i686-deb8-linux.tar.xz
Spider mode enabled. Check if remote file exists.
--2018-04-24 21:46:44--  http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i686-deb8-linux.tar.xz
Resolving downloads.haskell.org... 151.101.40.68
Connecting to downloads.haskell.org|151.101.40.68|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
```

As @cdsmith noted, the closest replacement is this URL:

http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i386-deb8-linux.tar.xz

... and we can verify that the URL works using:

```bash
$ wget --spider http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i386-deb8-linux.tar.xz
Spider mode enabled. Check if remote file exists.
--2018-04-24 21:47:54--  http://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i386-deb8-linux.tar.xz
Resolving downloads.haskell.org... 151.101.40.68
Connecting to downloads.haskell.org|151.101.40.68|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 112576160 (107M) [application/octet-stream]
Remote file exists.
```

The part of the script that is failing is this line:

```
run $DOWNLOADS               wget http://downloads.haskell.org/~ghc/$GHC_DIR/ghc-$GHC_VERSION-$GHC_ARCH.tar.xz
```

Specifically, the `GHC_ARCH` section needs to be changed since in the current script it is set to `i686-deb8-linux` but we need to fix it to be `i386-deb8-linux` instead.

The first thing to try is a blunt-force hammer.  Take these lines from the script:

```bash
if /sbin/ldconfig -p | grep -q libgmp.so.10; then
  GHC_ARCH=`uname -m`-deb8-linux
elif /sbin/ldconfig -p | grep -q libgmp.so.3; then
  GHC_ARCH=`uname -m`-centos67-linux
elif uname | grep -q Darwin; then
  GHC_ARCH=`uname -m`-apple-darwin
else
  echo Sorry, but no supported libgmp is installed.
  exit 1
fi
```

... and delete them and replace them with the hard-coded value that we want:

```
GHC_ARCH=i386-deb8-linux
```

... and then re-run the script to verify whether or not that fixes the immediate problem.  If it does then we can worry about the more general and portable solution.

**Comment by kammitama5** [comment]
Brute force works!

**Comment by cdsmith** [comment]
Great!  So what we've learned is that `uname -m` is not by itself enough to decide with CPU to download GHC for.  You might try something like this:

    case `uname -m` in
      i386)   GHC_CPU=i386;;
      i686)   GHC_CPU=i386;;
      x86_64) GHC_CPU=x86_64;;
      amd7)   GHC_CPU=amd7;;
    esac

Then you can use this CPU in the next statement:

    if /sbin/ldconfig -p | grep -q libgmp.so.10; then
      GHC_ARCH=`uname -m`-deb8-linux
    elif /sbin/ldconfig -p | grep -q libgmp.so.3; then
      GHC_ARCH=`uname -m`-centos67-linux
    elif uname | grep -q Darwin; then
      GHC_ARCH=`uname -m`-apple-darwin
    else
      echo Sorry, but no supported libgmp is installed.
      exit 1
    fi

This is still not perfect, because not all combinations of CPU and OS have downloads available.  But it's better, and good enough to get your build going.

**Comment by kammitama5** [comment]
Thank you! This is really helpful!

**Comment by kammitama5** [comment]
Yes, definitely worked! I can make a PR if need be. So much to learn :/

**Comment by cdsmith** [comment]
If you'd like to send a pull request to get used to the process, that sounds good to me.

**Comment by kammitama5** [comment]
did. It seems to be building. Just added the exception handling as Gabe suggested, also.
