### ISSUE TITLE
adding space after valid code results in endless compiling

### ISSUE THREAD

**Issue by mfourne** [google/codeworld#610]
Taking your first example from documentation, just adding a space after the first line results in codeworld not being able to compile the program.
Example:
program = drawingOf(wheel) 
wheel   = circle(2)
This holds true for real Haskell as well:
import CodeWorld
is valid. Adding a space gives a red screen without error message and a space plus newline gives "Compiling..." without end.

**Comment by jvoigtlaender** [comment]
To make this more clear:
* If the text in the editor window consists exactly of: first line `program = drawingOf(wheel)`, second line `wheel = circle(2)`, no further lines, then everything works as expected.
* If instead the text in the editor window consists exactly of: first line `program = drawingOf(wheel)[a space character added here]`, second line `wheel = circle(2)`, no further lines, then the site hangs, reproducibly.

The browser's web console indicates that the issue is a `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` at position 758:21 of `codeworld.js`. That position 758:21 is in the `var obj = JSON.parse(request.responseText);` line in the following code snippet:
```js
        var hash;
        var dhash;
        if (request.responseText.length == 23) {
          hash = request.responseText;
          dhash = null;
        } else {
          var obj = JSON.parse(request.responseText);
          hash = obj.hash;
          dhash = obj.dhash;
        }
```

**Comment by cdsmith** [comment]
This was due to the server running out of disk space in /tmp.  I've cleaned it up for now.

**Comment by jvoigtlaender** [comment]
Thank you!

I am now wondering whether we are responsible for this (increase of?) space consumption. We are running a Haskell course and are using CodeWorld for part of the exercises. We have explained to students how to install and use the `codeworld-api` package locally, but probably most are still using the online version.

Should we have "warned" you somehow that we are doing this course and using CodeWorld? (About 60-70 students take part in the exercises.)

**Comment by cdsmith** [comment]
It's not a problem.  I'm aware that temporary disk space usage grows over time on the server and needs cleaning from time to time.  I forgot to stay on top of it, and the alert seems to no longer be firing.  I'm looking into the latter issue.

**Comment by cdsmith** [comment]
That said, I am interested in your class.  It's nice to hear from others who are finding the platform useful.  If you wouldn't mind posting a brief overview of your class to https://groups.google.com/forum/#!forum/codeworld-discuss, I'd love to hear it.

**Comment by jvoigtlaender** [comment]
Cool. Will write a message about what we are doing, possibly with an example of exercises we are doing.
