### ISSUE TITLE
Color applied twice produces unexpected results

### ISSUE THREAD

**Issue by fernando-alegre** [google/codeworld#670]
This code will draw a blank output:
`program = drawingOf(colored( colored(solidCircle(5), RGBA(0,0,0,0)), blue))`

However, this code will draw a blue circle:
`program = drawingOf(colored( colored(solidCircle(5), RGBA(0,0,0,0.001)), blue))`

There is no apparent reason why `colored` is not continuous at (0,0,0,0)

**Comment by cdsmith** [comment]
The idea is that `Picture` embeds into `Point -> Color`, which gives it a consistent denotational semantics.  But the semantics imply that `colored(x, RGBA(r, g, b, 0))` should be the same as `blank`, since both pictures associate any point to a color that's completely transparent.  There are ways this could be handled such that `colored` is still continuous; for example, if `colored` multiplied alphas with the underlying image; but right now, what it tries to do is change any pixels with a non-transparent color to the new color.

By the way, I know these semantics don't actually work now.  The easiest counterexample is `colored(a & b, translucent(c))` where `a` and `b` are overlapping opaque shapes.  I intend to fix that, and it's tracked in #456.
