### ISSUE TITLE
Better visual design for error messages

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#764]
Instead of printing error messages as plain text in the console, they could be formatted as HTML elements, kind of like a "cards" UI.  The goals would be:

1. Make them more visual and less technical looking.  For example, add a fun-looking icon for errors or warnings.
2. Make them more noticeable.
3. Separate them more from standard console output (like stdout, or debug tracing)
4. Maybe hide the extra info such as stack traces and "in the expression..." until the card is expanded?

**Comment by nixorn** [comment]
Take a look on #825 . I integrated CodeMirror lint.js library, which highlights errors with warning/error icons, ref/yellow wavy underscores and annotations. #825 requires some testing, but if all is ok could we just delete plain text output?

**Comment by nixorn** [comment]
Seems like 1-3 mostly done in #825 . About what this task now?

**Comment by cdsmith** [comment]
Oh, I definitely wouldn't want to delete the output window, for a few reasons.  It's used for showing runtime errors (https://code.world/#Pt_6snLIVmNBs8BbFs8mfYw), tracing (https://code.world/#PO0tgsnd8mvcYrtyI1YQBmA), and standard output in Haskell mode (e.g., https://code.world/haskell#PfbhJUVgFOvmtZgrX2MWAhw).

Adding error icon to the errors (including runtime errors if possible), and warning icons to the warnings, would be a good step.  Making error messages collapsible would be good.

Separate cards for different outputs would be nice.  The compile errors would go on one card, and then stdout/stderr on a different one.  The cards could be expanded or collapsed independetly.  If there's a crash (https://github.com/google/codeworld/blob/master/web/js/run.js#L17 is called with true for the err arg), that would get added on yet another card as a new error on a card at the bottom.

**Comment by nixorn** [comment]
Thanks for clarification, especially for examples. I going to change `addMessage(isError, message)` to something like `addMessage(source, target, message)` where source is one of:
 
- `errorCheck` response
- [h$log](https://github.com/google/codeworld/blob/master/web/js/run.js#L64)
- [h$errorMsg](https://github.com/google/codeworld/blob/master/web/js/run.js#L71)
- [h$base_stdout_fd](https://github.com/google/codeworld/blob/master/web/js/run.js#L77)
- [h$base_stderr_fd](https://github.com/google/codeworld/blob/master/web/js/run.js#L78)

and target is one of cards. Formatting will depend from source.

By the way, why in this https://code.world/#PmZpNakgwPInEzBe0uwpL2Q example key input drops into `h$base_stderr_fd` instead of something like stdin?

**Comment by cdsmith** [comment]
I'm not sure I understand the question at the end, but the output to stderr comes from the `traced` function, which is used in the equation for `change` when a `KeyPress` event is received.
