### ISSUE TITLE
Handling randomness in Haskell mode

### ISSUE THREAD

**Issue by josephcsible** [google/codeworld#806]
I'm working on porting all of [the examples](https://github.com/google/codeworld/blob/39095f5ac8772f796d955b9db6e6da64195764a8/web/help/examples.md) to Haskell-mode, so that we'll have something useful in the guide besides a Haddock page in that mode. For the most part, this is straightforward. However, one part isn't: randomness. Consider this bit of the Bounce example:
```haskell
program = activityOf(initial, fine(change, 0.05), picture)

initial(x:y:vx:vy:_) = Ball((16*x  - 8, 16*y  - 8),
                            (16*vx - 8, 16*vy - 8))
```
There are two problems with porting that. First, as of commit 7b32720, the "magic" infinite random number list is no longer provided in Haskell mode. This problem is easy to resolve, like so:

```haskell
import System.Random

main = do
  g <- newStdGen
  activityOf (initial (randomRs (0, 1) g)) (fine change 0.05) picture

initial (x:y:vx:vy:_) = Ball (16*x  - 8, 16*y  - 8)
                             (16*vx - 8, 16*vy - 8)
```
However, there's a second problem that's more difficult to resolve cleanly. The above definition for `initial` results in this warning:
```
warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘initial’:
        Patterns not matched:
            []
            [_]
            [_, _]
            [_, _, _]
```
The problem here is that although the list from randomRs is infinite, the type system doesn't know this. Here's a few ideas I had for fixing this. First, passing an `StdGen` instead of a list:
```haskell
import Control.Monad.Random.Lazy

main = do
  g <- newStdGen
  activityOf (initial g) (fine change 0.05) picture

initial = evalRand $ do
    x <- r
    y <- r
    vx <- r
    vy <- r
    return (Ball (x , y )
                 (vx, vy))
 where r = getRandomR (-8, 8)
```
Upside: This is basically how the random number generator is intended to be used. Downside: monads are complicated.

Second, using an infinite list that is recognized as such by the type system:
```haskell
import qualified Data.InfList as InfList
import Data.InfList (InfList(..))
import System.Random

main :: IO ()
main = do
  g <- newStdGen
  activityOf (initial (InfList.unfoldr (randomR (0, 1)) g)) (fine change 0.05) picture

initial (x:::y:::vx:::vy:::_) = Ball (16*x  - 8, 16*y  - 8)
                                     (16*vx - 8, 16*vy - 8)
```
Upside: Looks and works very similarly to how regular CodeWorld does. Downside: A new complicated type to learn, and we'd have to add inflist as a dependency to CodeWorld.

Third, lifting the randommess work into main:
```haskell
import System.Random

main :: IO ()
main = do
  x <- randomRIO (-8, 8)
  y <- randomRIO (-8, 8)
  vx <- randomRIO (-8, 8)
  vy <- randomRIO (-8, 8)
  activityOf (Ball (x, y) (vx, vy)) (fine change 0.05) picture
```
Upside: Nice and simple. Downside: Doesn't work when you need an unbounded amount of random numbers in the change function, as the Asteroids example does.

Thoughts on how to handle this?

**Comment by cdsmith** [comment]
I like your first and third suggestions.  That is, either pass an StdGen, or generate the random numbers in the IO monad.  This is Haskell mode, so I think it's fine to expect that programmers can write normal Haskell code to handle an StdGen value when needed.

**Comment by josephcsible** [comment]
I think I'll go with passing the StdGen everywhere then, for consistency, since I can't use the third way in Asteroids.

> Perhaps another answer could be to turn off `-Wall`. It does tend to be a bit noisy

While this is true in general, I personally consider writing partial functions to be one of the greatest sins of Haskell, so I'd want that warning in particular to stay on by default even if `-Wall` weren't.

**Comment by josephcsible** [comment]
Another thought: what do you think of changing the signature of the event handling function from `Event -> world -> world` to `Event -> world -> IO world`? This would allow generating random numbers in IO even the way Asteroids needs to, without dragging in all of the new stuff from `Control.Monad.Random.Lazy`?

**Comment by cdsmith** [comment]
I agree that in standard Haskell, `StdGen` is a better answer than a list of untransformed numbers.  However, keep in mind that in certain specific cases, an infinite list of meaningful numbers, such as a list of times and positions at which things will appear in the future, can be more elegant than just keeping around an `StdGen`.  So I think this is really a case-by-case decision.

I agree that giving the event handling function an IO type is not a good solution to randomness.  It might not be so bad to have an IO version of `activityOf` for other reasons, though, such as adding networking, sound, or any other external behaviors.  At https://github.com/google/codeworld/pull/486, @nomeata even wired this up to Reflex to build an FRP interface, but it was never merged because of open questions about whether some of the code should go inside Reflex in a future version.  I'd like to merge that somehow in the future, too.  So there's room for exploration in more effectful programs in Haskell mode; I just don't think randomness is the right justification.

I'll try to convince you about partial functions, though.  In an educational environment, it's often better to let someone watch a thing fail, rather than prevent the failure.  Late failures have more context.  (For example, you might observe that a crash only happens when you've lost the game.)  This is the opposite of production environments, where you want failures to be caught as early as possible.

**Comment by cdsmith** [comment]
I think this question is answered.  Please reopen if there's part of the question that I missed.
