### ISSUE TITLE
Inconsistent sending of key press events

### ISSUE THREAD

**Issue by josephcsible** [google/codeworld#811]
**Shared Program**: https://code.world/#PL1P3DfDlbKvMjslV59Pugg

**Description**

When pressing and holding a key, it will continually send press events without intervening release events, but only if no other key has been pressed in the meantime. For example, if you press and hold the up key, a continuous stream of press events for it will be generated. However, if you tap and release the left key while still holding the up key, then no further press events for the up key will be generated until it's released and re-pressed. (A release event will still be generated for it once it's eventually released.)

This seems wrong to me. I don't think we should ever send more than one press event for a single press of the key. (After all, isn't this what we have release events for?) But if for some reason we do want to send multiple press events, why should pressing an unrelated key affect them?

**Comment by cdsmith** [comment]
This is the user's computer deciding to stop sending key events.  I'm not clear on whether that's a bug or not, because it's just not well-specified.  The computer is making a guess on what you meant, and its guess is that holding down a key means you want a lot of those, up until another key is pressed.

I'm sympathetic to your idea that autorepeat shouldn't happen for `KeyPress`.  Though this would break some student games that rely on it, I think it's okay most of the time.  But I'd rather combine this with an implementation of #460, so that we have a consistent story about how to handle text entry.

**Comment by cdsmith** [comment]
I think I'm okay with fixing this independent of #460 too, since text entry is currently so unreasonably hard that I doubt anyone does it much.  In any case, losing the repeat is a small loss.

**Comment by josephcsible** [comment]
Okay, here's how I think I'll solve this: create a new event type called KeyRepeat. For each key, keep track of whether a KeyPress or a KeyRelease was sent more recently. If a KeyPress comes when the last event for that key was also a KeyPress, then pass the new KeyRepeat event to the user's code instead of the KeyPress. Alternatively, if you think this event is unnecessary, I could just drop all of the repeats instead. Do either of these sound good?

**Comment by cdsmith** [comment]
I've now implemented #460.  However, in looking at this again, I am not sure that dropping autorepeat for `KeyPress` is the right thing to do.  For example, imagine trying to build a program with a text field.  Keys like Backspace and Left and Right will not generate `TextEntry` events, but they generally should still be auto-repeatable.

**Comment by cdsmith** [comment]
I think I'm going to just close this.  I'm in fact convinced that autorepeat should not be disabled.  It's far easier to ignore than it is to simulate.
